- tzatziki-spring-jpa/src/main/java/com/decathlon/tzatziki/steps/SpringJPASteps.java
Currently, while using the sentence like "that the DeliveryEventEntity entities will contain:", we get the following error:
I fixed that the same way than getRepositoryForTable works, filtering on our CrudRepository classes. It now works on my local env.
> fix: Use of TypeUtils to fix getRepositoryForEntity method

- mockfaster/src/main/java/com/decathlon/tzatziki/utils/MockFaster.java
- tzatziki-http/README.md
- tzatziki-http/src/main/java/com/decathlon/tzatziki/steps/HttpSteps.java
- tzatziki-logback/pom.xml
- tzatziki-spring/README.md
- tzatziki-spring/pom.xml
- tzatziki-spring/src/main/java/com/decathlon/tzatziki/spring/HttpInterceptor.java
- tzatziki-spring/src/main/java/com/decathlon/tzatziki/steps/SpringSteps.java
- tzatziki-spring/src/test/java/com/decathlon/tzatziki/app/TestApplication.java
- tzatziki-spring/src/test/java/com/decathlon/tzatziki/app/api/HelloController.java
- tzatziki-spring/src/test/java/com/decathlon/tzatziki/steps/TestApplicationSteps.java
- tzatziki-spring/src/test/resources/com/decathlon/tzatziki/steps/spring.feature
following https://github.com/Decathlon/tzatziki/discussions/17
This new HttpInterceptor class can intercept and rewrite the urls before any call from a RestTemplate or WebClient. 
That way we don't need to override the production urls in the test config.
If a mock exists, the url will be transparently replaced by the mock url and port.
(we now remap the mocks following this pattern to avoid collisions `/_mocked/{protocol}/{host}/{path}`)
This PR also fixes the local port glitch mentioned in the discussion.
> feat: added HttpInterceptor to rewrite url at the client level

- tzatziki-spring-jpa/src/main/java/com/decathlon/tzatziki/steps/SpringJPASteps.java
- tzatziki-spring-jpa/src/test/resources/com/decathlon/tzatziki/steps/spring-jpa.feature
When inserting data into tables where ids are auto generated and that I needed to link, I found no way of getting the value that was actually inserted in the DB. Either for testing DB triggers or low level transformations, I believe fetching data from the repositories is a common enough need to add this PR to the library. It simply does a findAll and store the content in a var. It follows ObjectSteps and SpringJPASteps naming conventions as close as possible.
> feat: extract data from repository

- mockfaster/pom.xml
- pom.xml
- tzatziki-common/pom.xml
- tzatziki-core/pom.xml
- tzatziki-core/src/main/java/com/decathlon/tzatziki/steps/ObjectSteps.java
- tzatziki-core/src/test/resources/com/decathlon/tzatziki/steps/objects.feature
- tzatziki-http/pom.xml
- tzatziki-logback/pom.xml
- tzatziki-spring-jpa/pom.xml
- tzatziki-spring-kafka/pom.xml
- tzatziki-spring/pom.xml
- tzatziki-testng/pom.xml
When collecting the values of a Datatable which contains null values, the `ObjectSteps#resolve` method throws a NullPointerException
Known bug from jdk https://bugs.openjdk.java.net/browse/JDK-8148463
> fix: Issue when a null is in a DataTable

- tzatziki-core/src/main/java/com/decathlon/tzatziki/steps/ObjectSteps.java
- tzatziki-core/src/test/resources/com/decathlon/tzatziki/steps/objects.feature
regression introduced in https://github.com/Decathlon/tzatziki/pull/31 (I accidently removed the `resolve` part in the `.put`)
> fix: regression on resolve object in DataTable

- mockfaster/src/main/java/com/decathlon/tzatziki/utils/MockFaster.java
- mockfaster/src/test/java/com/decathlon/tzatziki/utils/MockFasterTest.java
resetting the mockserver instance periodically fixes it for me. 
The default value is 400 but this can be configured using the `mockfaster.max-mocks` system property.
> fix for the max open files error on mac by resetting the mockserver after a given amount of mocks

- tzatziki-spring/src/main/java/com/decathlon/tzatziki/steps/SpringSteps.java
- tzatziki-spring/src/test/resources/com/decathlon/tzatziki/steps/spring.feature
Fixes cache assertion semantic that don't line up with common Tzatziki behaviour for the given `contains` assertion since it does an `exactly` comparison. Extends the use of the assertion to allow for `exactly` and other comparisons.
This fix is a breaking change for whoever expected the actual `the cache {} contains` guard to do an exact comparison.
> fix: spring cache comparison syntax and add comparison variations

- tzatziki-spring-jpa/src/main/java/com/decathlon/tzatziki/steps/SpringJPASteps.java
Temporary fix to avoid exceptions thrown in getRepositoryForTable if the application contains repository with inheritance.
Related to https://github.com/Decathlon/tzatziki/issues/88#issuecomment-1259495390
> fix: avoid NullPointerException in getRepositoryForTable if there is repositories with inheritance in the application

- tzatziki-logback/pom.xml
- tzatziki-logback/src/main/java/com/decathlon/tzatziki/steps/LoggerSteps.java
This PR solves the issue #106 by delegating the copy of the loglines to the orginal `List` within the `ListAppender` which methods are thread-safe but not resulting objects. Then the copy is used by AssertJ.
> fix: log assertions concurrent modification

- pom.xml
A vulnerability 9.8/10 has been detected on the commons-text 1.9.0 library
Correction : 
- Exclude it
- Uprgarde to the 1.10.0 version
https://commons.apache.org/proper/commons-text/security.html
** Note ** : this dependency is used by mockserver and in its new version 5.14.0, it still uses the vulnerable library
> Exclude the commons-text dependency

- tzatziki-spring-kafka/README.md
While testing we figured out that the consumer is not able to read some records, we investigated the issue and we have found that the producer is sending them before the consumer starts listening.  the config I add resolves the issue
> Fix consumer c'an't consume records

- mockfaster/src/main/java/com/decathlon/tzatziki/utils/MockFaster.java
- tzatziki-http/src/test/java/com/decathlon/tzatziki/steps/LimitWebsocketsSteps.java
- tzatziki-http/src/test/java/com/decathlon/tzatziki/steps/LocalSteps.java
- tzatziki-http/src/test/resources/com/decathlon/tzatziki/steps/http.feature
Circular map for registry is now properly handled by removing and adding back redefinitions of existing mocks to keep clientId in registry
> fix: http mock redefinitions always working

- mockfaster/src/main/java/com/decathlon/tzatziki/utils/MockFaster.java
- tzatziki-http/src/main/java/com/decathlon/tzatziki/steps/HttpSteps.java
- tzatziki-http/src/test/resources/com/decathlon/tzatziki/steps/http.feature
- If the url has query parameters and they contain empty brackets, they need to be escaped for the callback function in HttpSteps to complete normally. As done by ``escapeBrackets`` in MockFaster. 
- If the given step, has empty brackets but in the url path this time. Mockserver won't be able to compile the path url to a regex and crash. But for path url you can decode the empty brackets into their UTF-8 encoding, i.e.**%5B** for **[** and **%5D** for **]**, and mockserver will still match the request with the mock. 
- This method of using UTF-8 encoding for the brackets didn't work  for the query parameters, otherwise Mockserver won't be able to match the mock parameter with the real one, so we have to escape them.
> fix(issue #119): Escape empty brackets [] when present in query parameters

- tzatziki-common/src/main/java/com/decathlon/tzatziki/utils/Asserts.java
- tzatziki-common/src/test/java/com/decathlon/tzatziki/utils/AssertsTest.java
- tzatziki-core/src/test/java/com/decathlon/tzatziki/steps/AddCustomFlagSteps.java
I think that maybe using computeIfAbsent leads to a nicer result, what do you think?
(I also removed the split on `|` ... this is very specific to your inBounds example and can as well be done in the consumer)
> use computeIfAbsent to set the default consumers

- .github/workflows/build.yml
- mockfaster/pom.xml
- pom.xml
- tzatziki-spring-jpa/pom.xml
- tzatziki-spring-jpa/src/main/java/com/decathlon/tzatziki/steps/SpringJPASteps.java
- tzatziki-spring-jpa/src/main/java/com/decathlon/tzatziki/utils/PersistenceUtil.java
- tzatziki-spring-jpa/src/test/java/com/another_org/CorruptedEvilness.java
- tzatziki-spring-jpa/src/test/java/com/decathlon/tzatziki/app/TestApplication.java
- tzatziki-spring-jpa/src/test/java/com/decathlon/tzatziki/app/entity_listeners/SuperUserEntityListener.java
- tzatziki-spring-jpa/src/test/java/com/decathlon/tzatziki/app/model/Evilness.java
- tzatziki-spring-jpa/src/test/java/com/decathlon/tzatziki/app/model/Group.java
- tzatziki-spring-jpa/src/test/java/com/decathlon/tzatziki/app/model/SuperUser.java
- tzatziki-spring-jpa/src/test/java/com/decathlon/tzatziki/app/model/User.java
- tzatziki-spring-kafka/src/main/java/com/decathlon/tzatziki/steps/KafkaSteps.java
- tzatziki-spring-kafka/src/test/java/com/decathlon/tzatziki/kafka/KafkaConfig.java
- tzatziki-spring-kafka/src/test/java/com/decathlon/tzatziki/kafka/KafkaUsersListener.java
- tzatziki-spring/src/main/java/com/decathlon/tzatziki/steps/SpringSteps.java
Impacted Modules : 
- Parent : Upgrade the spring boot and the spring cloud version
- Spring Http : move the @LocalServerPort package
- Mockfaster : Upgrade the rest-assured module version
- Spring JPA : move the javax.persistence.* packages to jakarta.persistence.*
- Spring JPA : Move the jackson-datatype-hibernate5 to jackson-datatype-hibernate5-jakarta (the first one still uses javax.persistence.*)
- Spring Kafka : replace RecoveringBatchErrorHandler and SeekToCurrentErrorHandler classes with DefaultErrorHandler as they are now deprecated
> Add compatibility for Spring Boot 3.X.X (Jakarta / Kafka upgrade)

- tzatziki-spring/README.md
- tzatziki-spring/src/main/java/com/decathlon/tzatziki/steps/SpringSteps.java
- tzatziki-spring/src/test/java/com/decathlon/tzatziki/steps/TestApplicationSteps.java
- tzatziki-spring/src/test/resources/com/decathlon/tzatziki/steps/spring.feature
By default, the thread pool task executor queue is not clean between tests. 
If you want to enable the clean between tests:
```java
static {
SpringSteps.clearThreadPoolExecutor = true;
}
```
This clean can be very useful because we have seen some unpredictable behaviors during tests in our projects. It is due to background task from old test that is interfering with other test context.
> Add clear thread pool context function

- tzatziki-spring-jpa/pom.xml
- tzatziki-spring-kafka/pom.xml
- tzatziki-spring/pom.xml
- tzatziki-spring/src/main/java/com/decathlon/tzatziki/spring/HttpInterceptor.java
- tzatziki-spring/src/main/java/com/decathlon/tzatziki/steps/SpringSteps.java
- For non-web applications, spring web dependencies have been passed to the **provided** scope so as not to load them during the test phase.
- HttpInterceptor passed to **OnCondtionalWebApplication** because dependent on spring web, so non-web projects should not load it.
- For non-web projects, the **LocalServerPort** uses the @Value to have a default value.
> fix: none spring web app crashing because no "@LocalServerPort"

- tzatziki-spring/src/main/java/com/decathlon/tzatziki/spring/HttpInterceptor.java
Starting migration of our application to Spring boot 3, I've been struggling with some AOP issue : 
Could not generate CGLIB subclass of class org.springframework.security.config.annotation.method.configuration.PrePostMethodSecurityConfiguration
After some investigation, I found out it is because HttpInterceptor try to proxy PrePostMethodSecurityConfiguration which is a final class. 
This behavior can easily be reproduced with Spring security and the annotation @EnableMethodSecurity.
The quick fix I implemented is to adapt the Pointcut expression to not match final classes. 
It seems to fix the issue, I did not add test because it seem to be a really specific problem.
> Restrict HttpInterceptor AOP to none final class

- tzatziki-spring-jpa/pom.xml
- tzatziki-spring-kafka/pom.xml
- tzatziki-spring/src/main/java/com/decathlon/tzatziki/spring/DefaultWebClientDefinition.java
- tzatziki-spring/src/main/java/com/decathlon/tzatziki/spring/HttpInterceptor.java
- tzatziki-spring/src/main/java/com/decathlon/tzatziki/spring/HttpInterceptorDefinition.java
- tzatziki-spring/src/main/java/com/decathlon/tzatziki/spring/RestTemplateBuilderDefinition.java
- tzatziki-spring/src/main/java/com/decathlon/tzatziki/spring/RestTemplateDefinition.java
- tzatziki-spring/src/main/java/com/decathlon/tzatziki/spring/WebClientBuilderDefinition.java
Resolves #99 
With the version 1.3.9, we've made spring-boot-starter-webflux as _provided_. 
Trying to migrate my app to version 1.3.9 I was forced to add spring-boot-starter-webflux in my dependencies because HttpInterceptor in tzatziki-spring need it.
So I think it's best to use @Conditional spring condition to only inject bean related to web or webflux spring web dependencies depending of the application which is using tzatziki. 
It permit also to remove webflux test dependecies in jpa and kafka modules.
I am not strongly convinced of my approach so I'm open to suggestions. 
I have separate each type of interceptor tzatziki is putting to be sure to only try to intercept classes that are available on the classpath.
> Split HttpInterceptor to avoid spring web / webflux forced dependency

- pom.xml
- tzatziki-http/pom.xml
- tzatziki-jackson/src/main/java/com/decathlon/tzatziki/utils/JacksonMapper.java
Spring boot 3.1.0 imports jackson 2.15 dependency which change YamlFactoryBuilder default parser features. We have to enable YAMLParser.Feature.EMPTY_STRING_AS_NULL to maintain the same behavior.
https://github.com/FasterXML/jackson-dataformats-text/commit/f8f971327dbf4de9638fface7b37303a9691cca6
> Bump Spring boot to 3.1.0

- tzatziki-spring-jpa/src/main/java/com/decathlon/tzatziki/steps/SpringJPASteps.java
- tzatziki-spring-jpa/src/main/java/com/decathlon/tzatziki/utils/DatabaseCleaner.java
When datasource's autocommit is disable, DatabaseCleaner doesn't clean the table between each steps
> Wrap jdbcTemplate into transaction

- tzatziki-spring-kafka/src/main/java/com/decathlon/tzatziki/steps/KafkaSteps.java
- tzatziki-spring-kafka/src/test/resources/com/decathlon/tzatziki/steps/kafka.feature
Add support for Avro schemas that include arrays of nested records with a default value of null.
> fix: Support arrays with default null in Avro schema

- tzatziki-spring-jpa/README.md
- tzatziki-spring-jpa/src/main/java/com/decathlon/tzatziki/steps/SpringJPASteps.java
- tzatziki-spring-jpa/src/main/java/com/decathlon/tzatziki/utils/DatabaseCleaner.java
- tzatziki-spring-jpa/src/test/java/com/decathlon/tzatziki/app/dao/BookDataSpringRepository.java
- tzatziki-spring-jpa/src/test/java/com/decathlon/tzatziki/app/dao/ProductDataSpringRepository.java
- tzatziki-spring-jpa/src/test/java/com/decathlon/tzatziki/app/model/Book.java
- tzatziki-spring-jpa/src/test/java/com/decathlon/tzatziki/app/model/Product.java
- tzatziki-spring-jpa/src/test/java/com/decathlon/tzatziki/steps/TestApplicationSteps.java
- tzatziki-spring-jpa/src/test/resources/com/decathlon/tzatziki/steps/spring-jpa.feature
- tzatziki-spring-jpa/src/test/resources/db/migration/V1__schema.sql
Add the ability to specify schemas to clean in a List. 
In the code we prefix table names with schema => (schema.table) in SQL TRUNCATE commands.
We retrieve schema name from entity in the annotation `@Table` like we do for tableName.
Impacts : 
Property `(String) SpringJPASteps.schemaToClean` has been migrated to 
=>  `(List<String>) SpringJPASteps.schemasToClean`
Fix #344 
Fix #340
> Handle multiple db schema clean

- tzatziki-core/src/main/java/com/decathlon/tzatziki/utils/Patterns.java
- tzatziki-spring-kafka/src/main/java/com/decathlon/tzatziki/steps/KafkaSteps.java
- tzatziki-spring-kafka/src/test/resources/com/decathlon/tzatziki/steps/kafka.feature
🎯 This pull request aims to add dynamic management of topic names.
🤔 **Why ?** 
By allowing dynamic templates for topic names, we can replace parts of the topic with changing values. 
This will enable us to create unique topic names based on the environment (or other parameters), facilitating the testing of different conditions and scenarios with a single definition.
_Example: we run tests on ephemeral environments where topic names include a reference to the corresponding pull request : `pr-{pull_request_number}-topic-name`_
💡 That’s why, since this feature exists in different HTTP steps, it would be useful to also have the ability to use templates for the topic names in Kafka.
🙏🏼 Thank you for taking the time to review these changes!
> ✨ feat: template a value in the topic name

- tzatziki-common/src/main/java/com/decathlon/tzatziki/utils/TypeParser.java
Since upgrading to Spring Boot 3.4, we encountered issues with the tzatziki step:
> "receive a status X and a Response"
The error originates from the method TypeParser.parseType, which attempts to load a class that is not present in the classpath, causing a failure in the test execution.
I added error handling to catch this specific case and allow the correct class to be loaded afterward. This prevents the test from failing due to an unavailable class while ensuring the expected response is properly processed.
Let me know if any additional changes are needed! 🚀
> fix: catch errors in type parsing when there are multiple candidates

- pom.xml
- tzatziki-testng/pom.xml
Seems to be the reason the CI is not failing in case of Cucumber test error
Reverts Decathlon/tzatziki#495
> Revert "chore(deps): bump org.apache.maven.plugins:maven-surefire-plugin from 3.5.2 to 3.5.3"
